"""Configuration for authentication. Tune Argon2 values with the benchmark."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIRECTORY = PROJECT_ROOT / "data"
DATABASE_PATH = DATA_DIRECTORY / "users.db"

MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH = 32
USERNAME_PATTERN = r"^[A-Za-z0-9_]+$"
MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 128

ARGON2_ALGORITHM = "Argon2id"
ARGON2_SALT_LENGTH = 16
ARGON2_HASH_LENGTH = 32
ARGON2_MEMORY_COST = 32768  # KiB = 64 MiB
ARGON2_TIME_COST = 1
ARGON2_PARALLELISM = 1
ARGON2_VERSION = 19

LOGIN_CHALLENGE_LENGTH = 32
LOGIN_CHALLENGE_LIFETIME_SECONDS = 60
LOGIN_KEY_LABEL = b"SecureVault-Login-X25519-v1"
SESSION_TOKEN_LENGTH = 32
SESSION_LIFETIME_SECONDS = 30 * 60
DUMMY_SECRET_PATH = DATA_DIRECTORY / "dummy_login_secret.bin"